server:
  port: 8082
  tomcat:
    threads:
      max: 50 # 允许的最大线程数
    accept-count: 50 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
hm:
  db:
    database: hm-cart
    un: root
  swagger:
    title: 黑马商城购物车管理接口文档
    description: "黑马商城购物车接口文档"
    package: cart

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 #sentinel控制台地址
      http-method-specify: true