server:
  port: 8082
feign:
  okhttp:
    enabled: true
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
hm:
  db:
    database: hm-cart
    un: root
  swagger:
    title: 黑马商城购物车管理接口文档
    description: "黑马商城购物车接口文档"
    package: cart